# replace `lavastorm` with `{zone.short_name}`
# replace `zoneid = 27` with `zoneid = {zone.id}`

SELECT `short_name`, `id`, `file_name`, `long_name`, `map_file_name`, `safe_x`, `safe_y`, `safe_z`, `graveyard_id`, `min_level`, `min_status`, `zoneidnumber`, `version`, `timezone`, `maxclients`, `ruleset`, `note`, `underworld`, `minclip`, `maxclip`, `fog_minclip`, `fog_maxclip`, `fog_blue`, `fog_red`, `fog_green`, `sky`, `ztype`, `zone_exp_multiplier`, `walkspeed`, `time_type`, `fog_red1`, `fog_green1`, `fog_blue1`, `fog_minclip1`, `fog_maxclip1`, `fog_red2`, `fog_green2`, `fog_blue2`, `fog_minclip2`, `fog_maxclip2`, `fog_red3`, `fog_green3`, `fog_blue3`, `fog_minclip3`, `fog_maxclip3`, `fog_red4`, `fog_green4`, `fog_blue4`, `fog_minclip4`, `fog_maxclip4`, `fog_density`, `flag_needed`, `canbind`, `cancombat`, `canlevitate`, `castoutdoor`, `hotzone`, `insttype`, `shutdowndelay`, `peqzone`, `expansion`, `suspendbuffs`, `rain_chance1`, `rain_chance2`, `rain_chance3`, `rain_chance4`, `rain_duration1`, `rain_duration2`, `rain_duration3`, `rain_duration4`, `snow_chance1`, `snow_chance2`, `snow_chance3`, `snow_chance4`, `snow_duration1`, `snow_duration2`, `snow_duration3`, `snow_duration4`, `gravity`, `type`, `skylock` from zone where short_name = 'lavastorm';
SELECT `id`, `zone`, `version`, `number`, `y`, `x`, `z`, `heading`, `target_y`, `target_x`, `target_z`, `target_heading`, `zoneinst`, `target_zone_id`, `target_instance`, `buffer`, `client_version_mask` from zone_points WHERE zone = 'lavastorm';
SELECT `id`, `doorid`, `zone`, `version`, `name`, `pos_y`, `pos_x`, `pos_z`, `heading`, `opentype`, `guild`, `lockpick`, `keyitem`, `nokeyring`, `triggerdoor`, `triggertype`, `disable_timer`, `doorisopen`, `door_param`, `dest_zone`, `dest_instance`, `dest_x`, `dest_y`, `dest_z`, `dest_heading`, `invert_state`, `incline`, `size`, `buffer`, `client_version_mask`, `is_ldon_door` FROM doors where zone = 'lavastorm';
SELECT `id`, `zoneid`, `itemid`, `skill_level`, `chance`, `npc_id`, `npc_chance` FROM fishing where zoneid = 27;
SELECT `id`, `zoneid`, `Itemid`, `level`, `chance` FROM forage where zoneid = 27;
SELECT `id`, `zoneid`, `type`, `type2` FROM grid where zoneid = 27;
SELECT `gridid`, `zoneid`, `number`, `x`, `y`, `z`, `heading`, `pause` FROM grid_entries where zoneid = 27;
SELECT `id`, `zoneid`, `version`, `max_x`, `max_y`, `max_z`, `min_x`, `min_y`, `heading`, `name`, `item`, `max_allowed`, `comment`, `respawn_timer` FROM ground_spawns where zoneid = 27;
SELECT `id`, `zoneid`, `version`, `xpos`, `ypos`, `zpos`, `heading`, `itemid`, `charges`, `objectname`, `type`, `icon`, `unknown08`, `unknown10`, `unknown20`, `unknown24`, `unknown60`, `unknown64`, `unknown68`, `unknown72`, `unknown76`, `unknown84`, `size`, `tilt_x`, `tilt_y`, `display_name` from object WHERE zoneid = 27;
SELECT `id`, `name`, `lastname`, `level`, `race`, `class`, `bodytype`, `hp`, `mana`, `gender`, `texture`, `helmtexture`, `herosforgemodel`, `size`, `hp_regen_rate`, `mana_regen_rate`, `loottable_id`, `merchant_id`, `alt_currency_id`, `npc_spells_id`, `npc_spells_effects_id`, `npc_faction_id`, `adventure_template_id`, `trap_template`, `mindmg`, `maxdmg`, `attack_count`, `npcspecialattks`, `special_abilities`, `assistradius`, `face`, `luclin_hairstyle`, `luclin_haircolor`, `luclin_eyecolor`, `luclin_eyecolor2`, `luclin_beardcolor`, `luclin_beard`, `drakkin_heritage`, `drakkin_tattoo`, `drakkin_details`, `armortint_id`, `armortint_red`, `armortint_green`, `armortint_blue`, `d_melee_texture1`, `d_melee_texture2`, `ammo_idfile`, `prim_melee_type`, `sec_melee_type`, `ranged_type`, `runspeed`, `MR`, `CR`, `DR`, `FR`, `PR`, `Corrup`, `PhR`, `see_invis`, `see_invis_undead`, `qglobal`, `AC`, `npc_aggro`, `spawn_limit`, `attack_speed`, `attack_delay`, `findable`, `STR`, `STA`, `DEX`, `AGI`, `_INT`, `WIS`, `CHA`, `see_hide`, `see_improved_hide`, `trackable`, `isbot`, `exclude`, `ATK`, `Accuracy`, `Avoidance`, `slow_mitigation`, `version`, `maxlevel`, `scalerate`, `private_corpse`, `unique_spawn_by_name`, `underwater`, `isquest`, `emoteid`, `spellscale`, `healscale`, `no_target_hotkey`, `raid_target`, `armtexture`, `bracertexture`, `handtexture`, `legtexture`, `feettexture`, `light`, `walkspeed`, `peqid`, `unique_`, `fixed`, `ignore_despawn`, `show_name`, `untargetable` FROM npc_types WHERE id >= 27000 AND id < 28000;
SELECT `id`, `name`, `mincash`, `maxcash`, `avgcoin`, `done` FROM loottable WHERE id IN (SELECT `loottable_id` FROM npc_types WHERE id >= 27000 AND id < 28000);
SELECT `loottable_id`, `lootdrop_id`, `multiplier`, `probability`, `droplimit`, `mindrop` FROM loottable_entries WHERE loottable_id IN (SELECT `loottable_id` FROM npc_types WHERE id >= 27000 AND id < 28000);
SELECT `id`, `name` FROM lootdrop WHERE id IN (SELECT `lootdrop_id` FROM loottable_entries WHERE loottable_id IN (SELECT `loottable_id` FROM npc_types WHERE id >= 27000 AND id < 28000));
SELECT `lootdrop_id`, `item_id`, `item_charges`, `equip_item`, `chance`, `disabled_chance`, `minlevel`, `maxlevel`, `multiplier` FROM lootdrop_entries WHERE lootdrop_id IN (SELECT `lootdrop_id` FROM loottable_entries WHERE loottable_id IN (SELECT `loottable_id` FROM npc_types WHERE id >= 27000 AND id < 28000));
SELECT `id`, `zoneid`, `version`, `xpos`, `ypos`, `zpos`, `heading`, `itemid`, `charges`, `objectname`, `type`, `icon`, `unknown08`, `unknown10`, `unknown20`, `unknown24`, `unknown60`, `unknown64`, `unknown68`, `unknown72`, `unknown76`, `unknown84`, `size`, `tilt_x`, `tilt_y`, `display_name` FROM object WHERE zoneid = 27;
SELECT `zoneid`, `parentid`, `bagidx`, `itemid`, `charges`, `droptime`, `augslot1`, `augslot2`, `augslot3`, `augslot4`, `augslot5`, `augslot6` FROM object_contents WHERE zoneid = 27;
SELECT `zoneid`, `exploreid`, `minx`, `maxx`, `miny`, `maxy`, `minz`, `maxz` FROM proximities WHERE zoneid = 27;
SELECT `id`, `value`, `zone`, `instance_id` FROM spawn_condition_values WHERE zone = 'lavastorm';
SELECT `zone`, `id`, `value`, `onchange`, `name` FROM spawn_conditions WHERE zone = 'lavastorm';
SELECT `id`, `zone`, `cond_id`, `name`, `period`, `next_minute`, `next_hour`, `next_day`, `next_month`, `next_year`, `enabled`, `action`, `argument`, `strict` FROM spawn_events WHERE zone = 'lavastorm';
SELECT `id`, `spawngroupID`, `zone`, `version`, `x`, `y`, `z`, `heading`, `respawntime`, `variance`, `pathgrid`, `_condition`, `cond_value`, `enabled`, `animation` FROM spawn2 WHERE zone = 'lavastorm';
SELECT `spawngroupID`, `npcID`, `chance` FROM spawnentry WHERE spawngroupID IN (SELECT spawngroupid FROM spawn2 WHERE zone  = 'lavastorm');
SELECT `id`, `name`, `spawn_limit`, `dist`, `max_x`, `min_x`, `max_y`, `min_y`, `delay`, `mindelay`, `despawn`, `despawn_timer` FROM spawngroup WHERE id IN (SELECT spawngroupid FROM spawn2 WHERE zone  = 'lavastorm');
SELECT `id`, `zone`, `version`, `x`, `y`, `z`, `chance`, `maxzdiff`, `radius`, `effect`, `effectvalue`, `effectvalue2`, `message`, `skill`, `level`, `respawn_time`, `respawn_var`, `triggered_number`, `group`, `despawn_when_triggered` FROM traps WHERE zone = 'lavastorm';
